# Generated by Django 4.1.7 on 2023-04-26 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0011_alter_comment_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название группы')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Описание группы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/images', verbose_name='Фото группы')),
                ('is_closed_group', models.BooleanField(default=False, verbose_name='Закрыта ли группа')),
                ('group_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель группы')),
                ('group_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модерация группы')),
                ('posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='posts.post', verbose_name='Посты группы')),
                ('subscribers', models.ManyToManyField(blank=True, null=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='подписчики')),
            ],
        ),
    ]
