# Generated by Django 4.1.7 on 2023-04-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='posts',
        ),
    ]
