# Generated by Django 4.1.7 on 2023-04-26 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_remove_groups_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель группы'),
        ),
        migrations.RemoveField(
            model_name='groups',
            name='group_moderator',
        ),
        migrations.AlterField(
            model_name='groups',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='подписчики'),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_moderator',
            field=models.ManyToManyField(related_name='group_moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модерация группы'),
        ),
    ]
