# Generated by Django 4.1.7 on 2023-04-26 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_alter_groups_group_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_moderator',
            field=models.ManyToManyField(blank=True, related_name='group_moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модерация группы'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='подписчики'),
        ),
    ]
