# Generated by Django 4.1.7 on 2023-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groups_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Название группы в поиске'),
        ),
    ]
