# Generated by Django 4.1.7 on 2023-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_groups_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_slug',
            field=models.SlugField(unique=True, verbose_name='Название группы в поиске'),
        ),
    ]
