# Generated by Django 4.1.7 on 2023-04-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0014_remove_complaints_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(choices=[('drugs', 'Публикация содержит пропоганду наркотиков'), ('child pornography', 'Публикация содержит детскую порнография')], max_length=200, verbose_name='Жалоба')),
                ('complaint_status', models.CharField(choices=[('in_process', 'Жалоба на рассмотрении'), ('done', 'Жалоба рассмотрена'), ('not substantiated', 'Жалоба не обоснована')], default='Жалоба на рассмотрении', max_length=200, verbose_name='Статус жалобы')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='пост на который поступила жалоба')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь оставивший жалобу')),
            ],
            options={
                'verbose_name': 'Жалоба на пост',
                'verbose_name_plural': 'Жалобы на пост',
            },
        ),
        migrations.CreateModel(
            name='CommentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(choices=[('drugs', 'Публикация содержит пропоганду наркотиков'), ('child pornography', 'Публикация содержит детскую порнография')], max_length=200, verbose_name='Жалоба')),
                ('complaint_status', models.CharField(choices=[('in_process', 'Жалоба на рассмотрении'), ('done', 'Жалоба рассмотрена'), ('not substantiated', 'Жалоба не обоснована')], default='Жалоба на рассмотрении', max_length=200, verbose_name='Статус жалобы')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='комментарий на который поступила жалоба')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь оставивший жалобу')),
            ],
            options={
                'verbose_name': 'Жалоба на комментарий',
                'verbose_name_plural': 'Жалобы на комментарии',
            },
        ),
    ]
