# Generated by Django 4.1.7 on 2023-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_commentcomplaint_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentcomplaint',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='commentcomplaint',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='groupcomplaint',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='groupcomplaint',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='postcomplaint',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postcomplaint',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='commentcomplaint',
            name='complaint',
            field=models.CharField(choices=[], max_length=200, verbose_name='Жалоба'),
        ),
        migrations.AlterField(
            model_name='groupcomplaint',
            name='complaint',
            field=models.CharField(choices=[], max_length=200, verbose_name='Жалоба'),
        ),
        migrations.AlterField(
            model_name='postcomplaint',
            name='complaint',
            field=models.CharField(choices=[], max_length=200, verbose_name='Жалоба'),
        ),
    ]
