# Generated by Django 4.1.7 on 2023-04-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('complaints', '0003_remove_commentcomplaint_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcomplaint',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='commentcomplaint',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupcomplaint',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='groupcomplaint',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcomplaint',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='postcomplaint',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentcomplaint',
            name='complaint',
            field=models.CharField(choices=[('drugs', 'Публикация содержит пропоганду наркотиков'), ('child pornography', 'Публикация содержит детскую порнография')], max_length=200, verbose_name='Жалоба'),
        ),
        migrations.AlterField(
            model_name='groupcomplaint',
            name='complaint',
            field=models.CharField(choices=[('drugs', 'Публикация содержит пропоганду наркотиков'), ('child pornography', 'Публикация содержит детскую порнография')], max_length=200, verbose_name='Жалоба'),
        ),
        migrations.AlterField(
            model_name='postcomplaint',
            name='complaint',
            field=models.CharField(choices=[('drugs', 'Публикация содержит пропоганду наркотиков'), ('child pornography', 'Публикация содержит детскую порнография')], max_length=200, verbose_name='Жалоба'),
        ),
    ]
