# Generated by Django 4.1.7 on 2023-04-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_commentcomplaint_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentcomplaint',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='commentcomplaint',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='groupcomplaint',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='groupcomplaint',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='postcomplaint',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postcomplaint',
            name='object_id',
        ),
    ]
