# Generated by Django 4.1.7 on 2023-04-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(choices=[('drugs', 'Публикация содержит пропоганду наркотиков'), ('child pornography', 'Публикация содержит детскую порнография')], max_length=200, verbose_name='Жалоба')),
                ('complaint_status', models.CharField(choices=[('in_process', 'Жалоба на рассмотрении'), ('done', 'Жалоба рассмотрена'), ('not substantiated', 'Жалоба не обоснована')], default='Жалоба на рассмотрении', max_length=200, verbose_name='Статус жалобы')),
            ],
        ),
        migrations.CreateModel(
            name='Created',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
                ('image', models.ImageField(blank=True, help_text='Загрузить изображение к посту', null=True, upload_to='posts/images/%Y/%m/', verbose_name='Изображение')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='CommentComplaint',
            fields=[
                ('complaints_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.complaints')),
            ],
            options={
                'verbose_name': 'Жалоба на комментарий',
                'verbose_name_plural': 'Жалобы на комментарии',
            },
            bases=('posts.complaints',),
        ),
        migrations.CreateModel(
            name='PostComplaint',
            fields=[
                ('complaints_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.complaints')),
            ],
            options={
                'verbose_name': 'Жалоба на пост',
                'verbose_name_plural': 'Жалобы на пост',
            },
            bases=('posts.complaints',),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('created_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.created')),
            ],
            options={
                'verbose_name': 'Лайк к посту',
                'verbose_name_plural': 'Лайки к постам',
                'db_table': 'post_likes',
                'ordering': ['-created'],
            },
            bases=('posts.created', models.Model),
        ),
    ]
