# Generated by Django 4.1.7 on 2023-04-10 11:21

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_user_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='post', chained_model_field='post', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment'),
        ),
    ]
