# Generated by Django 4.1.7 on 2023-04-10 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_complaints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='comment',
        ),
        migrations.AddField(
            model_name='complaints',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь оставивший жалобу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint',
            field=models.CharField(choices=[('drugs', 'Публикация содержит пропоганду наркотиков'), ('child pornography', 'Публикация содержит детскую порнография')], max_length=200, verbose_name='Жалоба'),
        ),
        migrations.CreateModel(
            name='PostComplaint',
            fields=[
                ('complaints_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.complaints')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='пост на который поступила жалоба')),
            ],
            bases=('posts.complaints',),
        ),
        migrations.CreateModel(
            name='CommentComplaint',
            fields=[
                ('complaints_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.complaints')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='комментарий на который поступила жалоба')),
            ],
            bases=('posts.complaints',),
        ),
    ]
