# Generated by Django 4.1.7 on 2023-04-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_complaints_comment_complaints_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentcomplaint',
            options={'verbose_name': 'Жалоба на комментарий', 'verbose_name_plural': 'Жалобы на комментарии'},
        ),
        migrations.AlterModelOptions(
            name='postcomplaint',
            options={'verbose_name': 'Жалоба на пост', 'verbose_name_plural': 'Жалобы на пост'},
        ),
        migrations.AddField(
            model_name='complaints',
            name='complaint_status',
            field=models.CharField(choices=[('drugs', 'Публикация содержит пропоганду наркотиков'), ('child pornography', 'Публикация содержит детскую порнография')], default='in_process', max_length=200, verbose_name='Статус жалобы'),
        ),
    ]
