# Generated by Django 4.1.7 on 2023-04-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_commentcomplaint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='complaint_status',
        ),
    ]
