# Generated by Django 4.1.7 on 2023-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_complaints_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint_status',
            field=models.CharField(choices=[('done', 'Жалоба рассмотрена'), ('in_process', 'Жалоба на рассмотрении'), ('not substantiated', 'Жалоба не обоснована')], default='done', max_length=200, verbose_name='Статус жалобы'),
        ),
    ]
