# Generated by Django 4.1.7 on 2023-04-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postcomplaint',
            name='complaints_ptr',
        ),
        migrations.RemoveField(
            model_name='postcomplaint',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentComplaint',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.DeleteModel(
            name='PostComplaint',
        ),
    ]
