# Generated by Django 4.1.7 on 2023-04-12 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=79780432304, max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{11}$', message='Номер телефона должен содержать ровно 11 цифр.')], verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
