# Generated by Django 4.1.7 on 2023-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='application_status',
            field=models.CharField(choices=[('approved', 'заявка принята'), ('pending', 'заявка в ожидании'), ('decline', 'заявка отклонена')], default='заявка в ожидании', max_length=20),
        ),
    ]
