# Generated by Django 4.1.7 on 2023-04-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_friends_friend_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('user_profile', 'friend_request_sender')},
        ),
    ]
