name: SPRW-Socail

on: [ push ]

jobs:
  send_message_telegram:
    runs-on: ubuntu-latest
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Push в ветку ${{ github.ref_name }} выполнил ${{ github.actor }}
          с сообщением - ${{ github.event.commits[0].message }}.
          Ссылка на commit - https://github.com/${{ github.repository }}/commit/${{github.sha}}
